### ISSUE TITLE
Plugin does not appear to support grafana template variables

### ISSUE THREAD

**Issue by elfchief** [wavefrontHQ/grafana-wavefront-datasource#2]
I make use of templates somewhat extensively in grafana ("display the following for each GPS satellite"), and while switching over my graphs to use wavefront as a data source, I've run into an issue... template variables don't appear to work!

For example, I identify a GPS satellite by using a point tag of 'prn'. If I query on "gps.sats.azimuth_deg" and use a filter of "prn=1", I get the data I expect. If I change it to "prn=$prn" (where $prn==1), I get no datapoints and a warning of "Tag: [prn={1}] does not exist". This is slightly problematic!

This is using grafana 4.4.3 and grafana-wavefront-datasource@dd52ce6 (which is the latest)

**Comment by puckpuck** [comment]
Fixed by PR #3
