### ISSUE TITLE
Build Error - "Cannot find name '$'."

### ISSUE THREAD

**Issue by maxwell-gregory** [wavefrontHQ/grafana-wavefront-datasource#5]
When running `npm run build` I receive the following error:
```
> grafana-plugin@2.0.0 build /Users/mgregor/rep/ARM-> grafana-plugin@2.0.0 build /Users/mgregor/rep/grafana-wavefront-datasource
> rm -rf ./dist && ./node_modules/.bin/tsc && cp ./src/plugin.json ./dist && cp -r ./src/partials ./dist && cp -r ./src/css ./dist  && cp -r ./src/img ./dist && cp ./src/plugin/*.js ./dist/plugin

src/plugin/datasource.ts(33,22): error TS2304: Cannot find name '$'.
```

Please advise. I did not know how to perform step "Update files" either, I assumed it was an `npm update` more specificity on this would help

**Comment by puckpuck** [comment]
"Update files" means you modify and updating the pluging for your specific development needs.

Looks like the error you are seeing is because a `@types/jquery` dependency is missing.  I'm going to add it and get it merged into the master

**Comment by puckpuck** [comment]
It should be fixed now, please try again and re-open or create a new issue if you have any problems.
