### ISSUE TITLE
Typo (bug?) in config.html prevents setting Wavefront query timeout >6s

### ISSUE THREAD

**Issue by HandsomeWins** [wavefrontHQ/grafana-wavefront-datasource#6]
The config.html files have the max value for timeout listed as "6", instead of "60" (if I had to guess)? 

_<input type="number" class="gf-form-input max-width-24" ng-model="ctrl.current.jsonData.timeoutSecs" min="5" **max="6"** placeholder="auto" empty-to-null/>_

I changed this value manually, and some of my longer-running Wavefront queries succeeded, where before they were not.

**Comment by panghy** [comment]
Thanks!
